### ISSUE TITLE
empty lines cause invalid parsing

### ISSUE THREAD

**Issue by jsymfony** [tj/js-yaml#49]
``` yml
services:
    foo:
        a: 1

    bar:
        b: 2
```

and 

``` yml
services:
    foo:
        a: 1
    bar:
        b: 2
```

Parses differently (first example skips bar)
